export const config = {
    backgroundColor: '#e4f1fd',
    primaryColor: '#F4537B',
    white: '#ffffff',
    black: '#000000',
    yellow: '#ffce00',
    borderColor: '#1a1a1a',
    placeHolderColor: '#757575',
    fontPrimary:'OpenSans-Light',
    fontSecondary:'OpenSans-Regular',
    fontBold:'OpenSans-Bold',
    fontBoldType:'OpenSans-ExtraBold',
    fsSmall:12,
    fsMSmall:14,
    fsRegular:16,
    fsMedium:22,
    fsLarge:26,
    fsXL:32,
    lHeight:24,
};